const PDFDocument = require("pdfkit");

/**
 * Generates a FarmScore PDF report and resolves with a Buffer.
 * Requires: npm install pdfkit
 */
function generateReport(farmData) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const {
        farmerName = "N/A",
        landArea = "N/A",
        latitude = "N/A",
        longitude = "N/A",
        cropType = "N/A",
        score = "N/A",
        breakdown = {},
      } = farmData;

      // Header
      doc
        .fontSize(20)
        .fillColor("#1b5e20")
        .text("FarmScore AI — Credit Risk Report", { align: "center" });
      doc.moveDown(1.5);

      // Farm details
      doc.fontSize(13).fillColor("#000");
      doc.text(`Farmer Name: ${farmerName}`);
      doc.text(`Land Area: ${landArea} acres`);
      doc.text(`Location: ${latitude}, ${longitude}`);
      doc.text(`Primary Crop: ${cropType}`);
      doc.moveDown();

      // Score
      doc
        .fontSize(18)
        .fillColor("#1b5e20")
        .text(`FarmScore: ${score} / 100`, { underline: true });
      doc.moveDown();

      // Breakdown
      doc.fontSize(13).fillColor("#000").text("Score Breakdown:");
      doc.moveDown(0.5);
      Object.entries(breakdown).forEach(([key, value]) => {
        doc.text(`• ${key}: ${value}`);
      });

      doc.moveDown(2);
      doc
        .fontSize(9)
        .fillColor("#666")
        .text(
          "This report is generated by FarmScore-AI and is intended for internal credit assessment purposes only.",
          { align: "left" }
        );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateReport };
